
POST  http://localhost:3000/api/login HTTP/1.1
content-type: application/json

{    
    "user": "KMG",
    "password" : "123"
}


### 

GET  http://localhost:3000/api/users HTTP/1.1
content-type: application/json


### 


POST  http://localhost:3000/api/register HTTP/1.1
content-type: application/json

{
   "name":"Ana",
   "lastname1":"Sanchez",
   "lastname2":"Pérez",
   "age":15,
   "sex":"F",
   "country":"España",
   "lang_desired":[
      {
         "name":"Inglés"
      }
   ],
   "lang_teach":[
      {
         "name":"Español"
      }
   ],
   "hobbies":[
      {
         "name":"Bailar"
      }
   ],
   "contact":[
      {
         "name":"Whatsapp"
      }
   ]
}


### 