
POST  http://localhost:3000/api/login HTTP/1.1
content-type: application/json

{    
    "user": "VM",
    "password" : "123"
}


### 

GET  http://localhost:3000/api/users HTTP/1.1
content-type: application/json


### 


POST  http://localhost:3000/api/register HTTP/1.1
content-type: application/json

{
   "user": "SSM",
    "password" : "123",
   "name":"Sarah",
   "lastname1":"Scheneider",
   "lastname2":"Muls",
   "age":40,
   "sex":"F",
   "country":"Alemania",
   "lang_desired":[
      {
         "name":"Inglés"
      }
   ],
   "lang_teach":[
      {
         "name":"Alemán"
      }
   ],
   "contact":[
      {
         "name":"Skype"
      }
   ]
}


### 


POST  http://localhost:3000/api/exists HTTP/1.1
content-type: application/json

{    
    "user": "VMG"
}


### 


PUT  http://localhost:3000/api/addHobby HTTP/1.1
content-type: application/json

{    
    "user": "ATP",
    "name" : "Correr"
}


### 


DELETE   http://localhost:3000/api/deleteHobby HTTP/1.1
content-type: application/json

{    
    "user": "ATP",
    "name" : "Correr"
}


### 